name: Deploy static application

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Fix permissions
        run: |
          chmod -v -R +rX "static/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        path: "static/"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
